version: "3"

networks:
  shared:
    external: true

services:
  api:
    environment:
      VIRTUAL_HOST: infecshot.hysrtr.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: infecshot.hysrtr.com
      LETSENCRYPT_EMAIL: hys.rtr.forit@gmail.com
    networks:
      - shared 
