// Code generated by MockGen. DO NOT EDIT.
// Source: uuid.go

// Package mock_utils is a generated GoMock package.
package mock_utils

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUUIDInterface is a mock of UUIDInterface interface.
type MockUUIDInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDInterfaceMockRecorder
}

// MockUUIDInterfaceMockRecorder is the mock recorder for MockUUIDInterface.
type MockUUIDInterfaceMockRecorder struct {
	mock *MockUUIDInterface
}

// NewMockUUIDInterface creates a new mock instance.
func NewMockUUIDInterface(ctrl *gomock.Controller) *MockUUIDInterface {
	mock := &MockUUIDInterface{ctrl: ctrl}
	mock.recorder = &MockUUIDInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUIDInterface) EXPECT() *MockUUIDInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUUIDInterface) Get() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUUIDInterfaceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUUIDInterface)(nil).Get))
}
