// Code generated by MockGen. DO NOT EDIT.
// Source: uuid.go

// Package mock_utils is a generated GoMock package.
package mock_utils

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUUID is a mock of UUID interface.
type MockUUID struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDMockRecorder
}

// MockUUIDMockRecorder is the mock recorder for MockUUID.
type MockUUIDMockRecorder struct {
	mock *MockUUID
}

// NewMockUUID creates a new mock instance.
func NewMockUUID(ctrl *gomock.Controller) *MockUUID {
	mock := &MockUUID{ctrl: ctrl}
	mock.recorder = &MockUUIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUID) EXPECT() *MockUUIDMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUUID) Get() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUUIDMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUUID)(nil).Get))
}
