// Code generated by MockGen. DO NOT EDIT.
// Source: ranking.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	service "InfecShotAPI/pkg/server/service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRankingService is a mock of RankingService interface.
type MockRankingService struct {
	ctrl     *gomock.Controller
	recorder *MockRankingServiceMockRecorder
}

// MockRankingServiceMockRecorder is the mock recorder for MockRankingService.
type MockRankingServiceMockRecorder struct {
	mock *MockRankingService
}

// NewMockRankingService creates a new mock instance.
func NewMockRankingService(ctrl *gomock.Controller) *MockRankingService {
	mock := &MockRankingService{ctrl: ctrl}
	mock.recorder = &MockRankingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingService) EXPECT() *MockRankingServiceMockRecorder {
	return m.recorder
}

// GetRankInfoList mocks base method.
func (m *MockRankingService) GetRankInfoList(serviceRequest *service.GetRankInfoListRequest) (*service.GetRankInfoListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRankInfoList", serviceRequest)
	ret0, _ := ret[0].(*service.GetRankInfoListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRankInfoList indicates an expected call of GetRankInfoList.
func (mr *MockRankingServiceMockRecorder) GetRankInfoList(serviceRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRankInfoList", reflect.TypeOf((*MockRankingService)(nil).GetRankInfoList), serviceRequest)
}
