name: ci

on:
  pull_request:
    branches: [ develop, master ]

jobs:

  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run:  go build -v ./...

    - name: Unit Test
      run:  go test ./pkg/...

    - name: Integration Test
      run:  |
        cp .env.example .env
        docker network create loki
        make local
        docker-compose -f docker-compose.yml -f docker-compose.local.yml run -e MYSQL_HOST=mysql MYSQL_DATABASE=proto_api_test api go test ./e2e/...
