name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  deploy:
    name: Deploy
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $HOST_NAME
            User $USER_NAME
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
      - name: Stop the server
        run: ssh prod 'cd ~/InfecShotAPI/ && sudo pkill -e go && sudo pkill -e main'

      - name: Git pull
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: ssh prod 'cd ~/InfecShotAPI/ && git remote set-url origin https://'${GIT_USERNAME}':'${GIT_PASSWORD}'@github.com/Ryotaro-Hayashi/InfecShotAPI.git && git pull origin master'

      - name: Start the server
        run: |
          ssh prod 'cd ~/InfecShotAPI/ && docker exec infecshot-api nohup go run cmd/main.go >/dev/null 2>&1 &'
