name: Go

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

  #    - name: Test
  #      run: go test -v ./...

  deploy:
    # if: github.ref == 'refs/heads/master'
    needs: [ build ]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $HOST_NAME
            User $USER_NAME
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: Stop the server
        run: ssh staging 'cd ~/2103_proto_f_server/ && pkill -e go && pkill -e main'

      - name: Git pull
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: ssh staging 'cd ~/2103_proto_f_server/ && git remote set-url origin https://'${GIT_USERNAME}':'${GIT_PASSWORD}'@github.com/CyberAgentHack/2103_proto_f_server.git && git pull origin main'

      - name: Start the server
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        run: |
          ssh staging 'cd 2103_proto_f_server && MYSQL_USER='${MYSQL_USER}' MYSQL_PASSWORD='${MYSQL_PASSWORD}' MYSQL_HOST='${MYSQL_HOST}' MYSQL_PORT='${MYSQL_PORT}' MYSQL_DATABASE='${MYSQL_DATABASE}' nohup go run cmd/main.go &'
